### ISSUE TITLE
Pass only necessary data when create PageReader

### ISSUE THREAD

**Issue by ygf11** [jorgecarleitao/parquet2#135]
The new method of `PageReader` needs `&ColumnChunkMetaData` while it only use a small part of input.
 
In most scenarios, it is not the problem.
https://github.com/jorgecarleitao/parquet2/blob/fa6fa3ca3848c29d8efa80fbf42ee6a5a58cb077/src/read/page/reader.rs#L53-L58

However, user may not invoke `read_metadata()`before read page data, such as using the cached data, which is a necessary part of `ColumnChunkMetaData`. Then it is not easy to create a `PageReader`, because `ColumnChunkMetaData` is huge, and `column_chunk` is even in another crate.

How about adding a new constructor for `PageReader`, like: 
```rust
pub struct PageMetaData {
    pub num_values: i64,
    pub compression: Compression,
    pub descriptor: ColumnDescriptor,
}
pub fn new_with_page_meta(
        reader: R,
        column: PageMetaData,
        pages_filter: PageFilter,
        buffer: Vec<u8>,
    ) -> Self {
        Self {
            reader,
            total_num_values: column.num_values,
            compression: column.compression,
            seen_num_values: 0,
            current_dictionary: None,
            descriptor: column.descriptor.descriptor,
            pages_filter,
            buffer,
        }
    }
```

**Comment by jorgecarleitao** [comment]
Agree - we should only require the minimum to create the page reader.
