### ISSUE TITLE
Async FileStreamer does not write statistics

### ISSUE THREAD

**Issue by TurnOfACard** [jorgecarleitao/parquet2#139]
Compare:

https://github.com/jorgecarleitao/parquet2/blob/47edd88ab831da74c5e17d7b0e483ddc243f0f6a/src/write/file.rs#L123-L186

https://github.com/jorgecarleitao/parquet2/blob/47edd88ab831da74c5e17d7b0e483ddc243f0f6a/src/write/stream.rs#L119-L137

**Comment by jorgecarleitao** [comment]
indeed, it slipped - would you like to PR it or should I?

**Comment by TurnOfACard** [comment]
I'm happy to look into it; I could perhaps check it out next weekend?
