### ISSUE TITLE
Feature Request: Supports legacy lz4 decompression

### ISSUE THREAD

**Issue by dantengsky** [jorgecarleitao/parquet2#152]
It is really awkward to request this feature since `lz4` is deprecated in `parquet2`, but unfortunately:

- We have some legacy data that have been written using the legacy `lz4` compression algo, and backward compatibility is a must for us

- Although we have an internal patched branch of `parquet2` as a workaround, a "vanilla version" of `parquet2` is much much more preferred

Thus: Is it possible that `parquet2` supports legacy lz4 decompression?  (It is fully understandable that if this FR and the accompanied PR are rejected)

**Comment by jorgecarleitao** [comment]
We should definitely support it - I just did not have the time yet to work on this :( Would you be able/willing to work on it?

See also https://github.com/jorgecarleitao/arrow2/issues/954

**Comment by dantengsky** [comment]
>  Would you be able/willing to work on it?

Yeah, please take a look at PR 
- #151

looking forward to your feedback :)

**Comment by jorgecarleitao** [comment]
Closed by #151
