### ISSUE TITLE
Unnecessarily slow writes due to repeated flushes when writing to a BufWriter

### ISSUE THREAD

**Issue by cyr** [jorgecarleitao/parquet2#199]
I have an implementation using this library that writes parquet to an s3 bucket. I haven't particularly noticed the slowness of writing parquet earlier, I'll admit, but when writing batches over requests it became quite noticeable.

Since I'm using a BufWriter to wrap my output Write-implementation, I would expect that the buffer would be used as much as possible so I can define the size of each request sent to S3. However, this part here in write/column_chunk.rs:
```
    let mut protocol = TCompactOutputProtocol::new(writer);
    bytes_written += column_chunk
        .meta_data
        .as_ref()
        .unwrap()
        .write_to_out_protocol(&mut protocol)? as u64;
    protocol.flush()?;
```
.. ensures that the BufWriter flushes on each column-chunk written, which is detrimental to performance. I haven't looked too closely at the implementation of TCompactOutputProtocol, but I wouldn't think flushing the underlying writer is necessary here?

**Comment by jorgecarleitao** [comment]
Good point. This is not necessary, no. Would you be willing to audit our uses of `.flush` and PR accordingly?

**Comment by cyr** [comment]
I can do that. I've noticed similar issues in the arrow2 crate for arrow IPC writing, if you don't mind I could have a look at that part too?

**Comment by jorgecarleitao** [comment]
That would be awesome!
