### ISSUE TITLE
Report `RowGroup::file_offset`

### ISSUE THREAD

**Issue by jorgecarleitao** [jorgecarleitao/parquet2#52]
See https://github.com/apache/arrow/pull/11149/files#diff-a5c0680e0cdc891095924b93ac23383d3a962b7b929876818ecffe461f83b1cdR1571 on how it should be computed.

**Comment by barrotsteindev** [comment]
Hey @jorgecarleitao,
I started working on an initial implementation, but am not familiar with the test infra.
Is there any specific test I should add?
Do the tests cover this change, since I assume arrow and pyspark use this field?

Thanks in advance

**Comment by barrotsteindev** [comment]
Went in another direction to support `metadata#into_thrift`
Pr link: https://github.com/barrotsteindev/parquet2/pull/4

**Comment by jorgecarleitao** [comment]
Done in #81
